spring:
  redis:
    host: redis
    password: 3RgN4ThM
    port: 6379

zuul:
  routes:
    products:
      path: /products/**
      url: http://svc-product:8080/products
    cart:
      path: /cart/**
      url: http://svc-cart:8080/cart

shopcart:
  host:
    mongo: mongo
  database:
    name: products
